import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface Translations {
  [key: string]: string;
}

const enTranslations: Translations = {
  // Navigation
  nav_features: 'Features',
  nav_guides: 'Guides',
  nav_pricing: 'Pricing',
  nav_partners: 'Partners',
  nav_login: 'Log in',
  nav_signup: 'Sign up',
  nav_dashboard: 'Dashboard',
  nav_wallet: 'Wallet',
  nav_trips: 'Trips',
  nav_emergency: 'Emergency',
  nav_settings: 'Settings',
  nav_logout: 'Log out',
  nav_admin: 'Admin',
  nav_partner: 'Partner',
  nav_bookings: 'Bookings',
  nav_points: 'Points',
  nav_journal: 'Journal',

  // Hero
  hero_title: 'Your Intelligent Travel Companion',
  hero_subtitle: 'Plan, book, and explore with AI-powered recommendations, real-time safety insights, and seamless local payments.',
  hero_cta_primary: 'Start Your Journey',
  hero_cta_secondary: 'Watch Demo',
  hero_trust: 'Trusted by 50,000+ travelers across the Middle East & Africa',

  // Features
  features_title: 'Everything You Need to Travel Smarter',
  features_subtitle: 'From AI planning to emergency support, Voiago covers every aspect of your journey.',
  feature_ai_title: 'AI Trip Planner',
  feature_ai_desc: 'Get personalized itineraries in seconds. Our AI understands your preferences and local nuances.',
  feature_wallet_title: 'Smart Travel Wallet',
  feature_wallet_desc: 'Track expenses, split bills, and manage budgets across multiple currencies effortlessly.',
  feature_safety_title: 'Safety & SOS',
  feature_safety_desc: 'Real-time alerts, offline emergency protocols, and instant location sharing with trusted contacts.',
  feature_loyalty_title: 'Loyalty & Rewards',
  feature_loyalty_desc: 'Earn points on every booking. Unlock exclusive perks, upgrades, and partner discounts.',

  // Travel Guides
  guides_title: 'Curated Travel Guides',
  guides_subtitle: 'Discover hidden gems and local secrets from our community of explorers.',
  guides_read_more: 'Read Guide',
  guides_min_read: 'min read',

  // Pricing
  pricing_title: 'Simple, Transparent Pricing',
  pricing_subtitle: 'Choose the plan that fits your travel style. No hidden fees.',
  pricing_starter: 'Starter',
  pricing_pro: 'Pro',
  pricing_enterprise: 'Enterprise',
  pricing_month: '/month',
  pricing_popular: 'Most Popular',
  pricing_get_started: 'Get Started',
  pricing_contact_sales: 'Contact Sales',

  // Partners
  partners_title: 'Partner With Us',
  partners_subtitle: 'Join our ecosystem of hotels, tour operators, and local experience providers.',
  partners_cta: 'Become a Partner',

  // Footer
  footer_tagline: 'Your intelligent travel companion for the Middle East & Africa.',
  footer_product: 'Product',
  footer_company: 'Company',
  footer_legal: 'Legal',
  footer_rights: 'All rights reserved.',

  // Auth
  auth_welcome: 'Welcome Back',
  auth_welcome_sub: 'Sign in to access your travel dashboard',
  auth_email: 'Email Address',
  auth_password: 'Password',
  auth_sign_in: 'Sign In',
  auth_no_account: "Don't have an account?",
  auth_sign_up: 'Sign Up',
  auth_forgot_password: 'Forgot password?',
  auth_create_account: 'Create Account',
  auth_name: 'Full Name',
  auth_confirm_password: 'Confirm Password',
  auth_have_account: 'Already have an account?',
  auth_or_continue: 'Or continue with',
  auth_traveler: 'Traveler',
  auth_partner_role: 'Partner',
  auth_admin: 'Admin',
  auth_role_label: 'Account Type',

  // Dashboard
  dashboard_welcome: 'Welcome back',
  dashboard_subtitle: "Here's your smart travel ecosystem overview",
  dashboard_itinerary: 'Itinerary',
  dashboard_insights: 'Insights',
  dashboard_upcoming: 'Upcoming Trip',
  dashboard_days_until: 'days until departure',
  dashboard_destination: 'Destination',
  dashboard_travelers: 'Travelers',
  dashboard_budget: 'Budget',
  dashboard_spent: 'spent',
  dashboard_view_details: 'View Details',
  dashboard_active_trip: 'Active Trip',
  dashboard_wallet: 'Wallet',
  dashboard_safety_status: 'Safety Status',
  dashboard_safety_safe: 'Safe',
  dashboard_safety_moderate: 'Moderate',
  dashboard_safety_alert: 'Alert',
  dashboard_recent_activity: 'Recent Activity',
  dashboard_no_activity: 'No recent activity',
  dashboard_explore_more: 'Explore More',
  dashboard_book_next: 'Book Your Next Adventure',

  // Wallet
  wallet_title: 'Travel Wallet',
  wallet_subtitle: 'Manage your travel finances',
  wallet_balance: 'Available Balance',
  wallet_add_funds: 'Add Funds',
  wallet_send: 'Send',
  wallet_transactions: 'Transactions',
  wallet_expenses: 'Expenses',
  wallet_all: 'All',
  wallet_credits: 'Credits',
  wallet_debits: 'Debits',
  wallet_no_transactions: 'No transactions yet',
  wallet_expense_breakdown: 'Expense Breakdown',
  wallet_category_accommodation: 'Accommodation',
  wallet_category_food: 'Food & Dining',
  wallet_category_transport: 'Transport',
  wallet_category_activities: 'Activities',
  wallet_category_shopping: 'Shopping',
  wallet_category_other: 'Other',

  // Trip Planner
  planner_title: 'AI Trip Planner',
  planner_subtitle: 'Let our AI craft your perfect journey',
  planner_destination: 'Where do you want to go?',
  planner_dates: 'Travel Dates',
  planner_travelers: 'Number of Travelers',
  planner_budget: 'Budget Range',
  planner_preferences: 'Preferences',
  planner_generate: 'Generate Itinerary',
  planner_generating: 'Generating...',
  planner_day: 'Day',
  planner_morning: 'Morning',
  planner_afternoon: 'Afternoon',
  planner_evening: 'Evening',
  planner_save_trip: 'Save Trip',
  planner_share: 'Share',
  planner_modify: 'Modify',

  // Emergency
  emergency_title: 'Emergency Center',
  emergency_subtitle: 'Quick access to safety tools and emergency contacts',
  emergency_sos: 'SOS Alert',
  emergency_sos_desc: 'Send immediate alert with your location',
  emergency_contacts: 'Emergency Contacts',
  emergency_local_police: 'Local Police',
  emergency_ambulance: 'Ambulance',
  emergency_embassy: 'Embassy',
  emergency_share_location: 'Share Location',
  emergency_safety_map: 'Safety Map',
  emergency_status: 'Status',
  emergency_last_updated: 'Last updated',

  // Settings
  settings_title: 'Settings',
  settings_subtitle: 'Manage your account preferences',
  settings_profile: 'Profile',
  settings_notifications: 'Notifications',
  settings_privacy: 'Privacy',
  settings_language: 'Language',
  settings_currency: 'Currency',
  settings_save: 'Save Changes',
  settings_cancel: 'Cancel',
  settings_edit: 'Edit',
  settings_name: 'Name',
  settings_email: 'Email',
  settings_phone: 'Phone',
  settings_bio: 'Bio',

  // Points
  points_title: 'Loyalty Points',
  points_subtitle: 'Track and redeem your rewards',
  points_balance: 'Points Balance',
  points_history: 'Points History',
  points_redeem: 'Redeem',
  points_earn_more: 'Earn More',
  points_tier: 'Tier',
  points_next_tier: 'points to next tier',

  // Journal
  journal_title: 'Travel Journal',
  journal_subtitle: 'Capture and share your travel memories',
  journal_new_entry: 'New Entry',
  journal_no_entries: 'No journal entries yet',
  journal_write_first: 'Write your first entry',
  journal_date: 'Date',
  journal_location: 'Location',
  journal_mood: 'Mood',
  journal_tags: 'Tags',

  // Bookings
  bookings_title: 'My Bookings',
  bookings_subtitle: 'Manage your upcoming and past trips',
  bookings_upcoming: 'Upcoming',
  bookings_past: 'Past',
  bookings_cancelled: 'Cancelled',
  bookings_no_bookings: 'No bookings found',
  bookings_book_now: 'Book Now',
  bookings_details: 'Details',
  bookings_cancel: 'Cancel',
  bookings_modify: 'Modify',

  // Admin
  admin_title: 'Admin Dashboard',
  admin_subtitle: 'Manage platform operations',
  admin_users: 'Users',
  admin_partners: 'Partners',
  admin_bookings: 'Bookings',
  admin_revenue: 'Revenue',
  admin_analytics: 'Analytics',
  admin_support: 'Support Tickets',

  // Partner
  partner_title: 'Partner Dashboard',
  partner_subtitle: 'Manage your listings and bookings',
  partner_listings: 'My Listings',
  partner_bookings: 'Bookings',
  partner_reviews: 'Reviews',
  partner_analytics: 'Analytics',
  partner_payouts: 'Payouts',

  // AI Chatbot
  chat_title: 'Voiago AI',
  chat_placeholder: 'Ask me anything about your trip...',
  chat_send: 'Send',
  chat_suggestions: 'Suggestions',
  chat_plan_trip: 'Plan a trip',
  chat_find_hotels: 'Find hotels',
  chat_safety_info: 'Safety info',
  chat_clear: 'Clear chat',

  // Common
  common_loading: 'Loading...',
  common_error: 'Something went wrong',
  common_retry: 'Retry',
  common_save: 'Save',
  common_delete: 'Delete',
  common_edit: 'Edit',
  common_cancel: 'Cancel',
  common_confirm: 'Confirm',
  common_back: 'Back',
  common_next: 'Next',
  common_done: 'Done',
  common_search: 'Search',
  common_filter: 'Filter',
  common_sort: 'Sort',
  common_view_all: 'View All',
  common_show_more: 'Show More',
  common_show_less: 'Show Less',
  common_read_more: 'Read More',
  common_learn_more: 'Learn More',
  common_get_started: 'Get Started',
  common_contact: 'Contact',
  common_help: 'Help',
  common_support: 'Support',
  common_feedback: 'Feedback',
  common_share: 'Share',
  common_copy: 'Copy',
  common_copied: 'Copied!',
  common_close: 'Close',
  common_open: 'Open',
  common_select: 'Select',
  common_choose: 'Choose',
  common_apply: 'Apply',
  common_reset: 'Reset',
  common_update: 'Update',
  common_remove: 'Remove',
  common_add: 'Add',
  common_create: 'Create',
  common_new: 'New',
  common_active: 'Active',
  common_inactive: 'Inactive',
  common_pending: 'Pending',
  common_completed: 'Completed',
  common_failed: 'Failed',
  common_success: 'Success',
  common_warning: 'Warning',
  common_info: 'Info',
  common_error_occurred: 'An error occurred',
  common_try_again: 'Please try again',
  common_no_results: 'No results found',
  common_empty_state: 'Nothing here yet',
  common_coming_soon: 'Coming Soon',
  common_beta: 'Beta',
  common_new_feature: 'New Feature',
  common_popular: 'Popular',
  common_recommended: 'Recommended',
  common_featured: 'Featured',
  common_exclusive: 'Exclusive',
  common_limited: 'Limited Time',
  common_free: 'Free',
  common_premium: 'Premium',
  common_pro: 'Pro',
  common_basic: 'Basic',
  common_standard: 'Standard',
  common_enterprise: 'Enterprise',
  common_monthly: 'Monthly',
  common_yearly: 'Yearly',
  common_per_month: 'per month',
  common_per_year: 'per year',
  common_start_free: 'Start Free Trial',
  common_upgrade: 'Upgrade',
  common_downgrade: 'Downgrade',
  common_manage: 'Manage',
  common_configure: 'Configure',
  common_customize: 'Customize',
  common_personalize: 'Personalize',
  common_secure: 'Secure',
  common_private: 'Private',
  common_public: 'Public',
  common_visible: 'Visible',
  common_hidden: 'Hidden',
  common_enabled: 'Enabled',
  common_disabled: 'Disabled',
  common_on: 'On',
  common_off: 'Off',
  common_yes: 'Yes',
  common_no: 'No',
  common_ok: 'OK',
  common_continue: 'Continue',
  common_skip: 'Skip',
  common_back_to_home: 'Back to Home',
  common_go_to_dashboard: 'Go to Dashboard',
  common_explore: 'Explore',
  common_discover: 'Discover',
  common_plan: 'Plan',
  common_book: 'Book',
  common_track: 'Track',
  common_manage_account: 'Manage Account',
  common_profile_settings: 'Profile Settings',
  common_account_settings: 'Account Settings',
  common_notification_settings: 'Notification Settings',
  common_privacy_settings: 'Privacy Settings',
  common_security_settings: 'Security Settings',
  common_language_settings: 'Language Settings',
  common_currency_settings: 'Currency Settings',
  common_payment_methods: 'Payment Methods',
  common_billing: 'Billing',
  common_subscription: 'Subscription',
  common_invite_friends: 'Invite Friends',
  common_help_center: 'Help Center',
  common_terms: 'Terms of Service',
  common_privacy_policy: 'Privacy Policy',
  common_cookies: 'Cookie Policy',
  common_accessibility: 'Accessibility',
  common_about: 'About',
  common_careers: 'Careers',
  common_press: 'Press',
  common_blog: 'Blog',
  common_contact_us: 'Contact Us',

  // Notifications
  notif_title: 'Notifications',
  notif_mark_all_read: 'Mark all as read',
  notif_clear_all: 'Clear all',
  notif_no_notifications: 'No notifications',
  notif_flight_reminder: 'Flight Reminder',
  notif_check_in: 'Check-in Open',
  notif_safety_alert: 'Safety Alert',
  notif_points_earned: 'Points Earned',
  notif_booking_confirmed: 'Booking Confirmed',
  notif_payment_received: 'Payment Received',
  notif_new_message: 'New Message',
  notif_trip_update: 'Trip Update',
  notif_weather_alert: 'Weather Alert',
  notif_promo: 'Special Offer',

  // Additional keys
  common_sustainability: 'Sustainability Score',
  common_rating: 'Rating',
  common_places: 'Places',
  common_traveler: 'Traveler',
  common_quick_actions: 'Quick Actions',
  common_total: 'Total',
  common_adventure: 'Adventure',
  common_culture: 'Culture',
  common_food: 'Food',
  common_nature: 'Nature',
  common_relaxation: 'Relaxation',
  common_nightlife: 'Nightlife',
  common_budget: 'Budget',
  common_luxury: 'Luxury',
  common_days: 'days',
  common_activities: 'activities',
  common_all: 'All',
  common_challenges: 'Challenges',
  common_tiers: 'Tiers',
  common_progress: 'Progress',
  common_min: 'min',
  common_points: 'points',
  common_book_hotel: 'Book a Hotel',
  common_write_review: 'Write a Review',
  common_refer_friend: 'Refer a Friend',
  common_guests: 'guests',
  common_start_exploring: 'Start exploring to book your first trip',
  common_access_denied: 'Access Denied',
  common_admin_only: 'Admin access only',
  common_partner_only: 'Partner access only',
  common_overview: 'Overview',
  common_last_30_days: 'Last 30 days',
  common_last_90_days: 'Last 90 days',
  common_last_year: 'Last year',
  common_chart_coming_soon: 'Chart visualization coming soon',
  common_system_health: 'System Health',
  common_api_status: 'API Status',
  common_database: 'Database',
  common_cdn: 'CDN',
  common_operational: 'Operational',
  common_manage_users: 'Manage Users',
  common_approve_partners: 'Approve Partners',
  common_process_payouts: 'Process Payouts',
  common_add_listing: 'Add Listing',
  common_view_payouts: 'View Payouts',
  common_view_reviews: 'View Reviews',
  common_available: 'Available',
  common_total_earned: 'Total Earned',
  common_request_payout: 'Request Payout',
  common_map_loading: 'Map Loading',
  common_map_coming_soon: 'Interactive map coming soon',
  common_layer: 'Layer',
  common_safe: 'Safe',
  common_caution: 'Caution',
  common_alert: 'Alert',
  common_activate: 'Activate',
  common_sharing_location_in: 'Sharing location in',
  common_location_shared: 'Location Shared',
  common_contacts_notified: 'Contacts have been notified',
  common_share_again: 'Share Again',
  common_spent: 'Spent',
  common_english: 'English',
  common_arabic: 'Arabic',
  common_saved: 'Saved',
  privacy_location: 'Location Sharing',
  privacy_location_desc: 'Share your location with trusted contacts',
  privacy_profile: 'Profile Visibility',
  privacy_profile_desc: 'Control who can see your profile',
  privacy_data: 'Data Usage',
  privacy_data_desc: 'Manage how your data is used',
  notif_flight_desc: 'Your flight to Cairo departs in 24 hours',
  notif_checkin_desc: 'Check-in is now open for your booking',
  notif_safety_desc: 'Weather alert in your destination area',
  notif_points_desc: 'You earned 500 points for your last booking',
  notif_promo_desc: 'Get 20% off your next booking',
  settings_profile_desc: 'Update your personal information',
  journal_entry_title: 'Entry Title',
  journal_write_your_thoughts: 'Write your thoughts...',
  journal_tags_placeholder: 'Add tags separated by commas',

  // Accessibility
  a11y_skip_to_content: 'Skip to main content',
  a11y_menu: 'Menu',
  a11y_close_menu: 'Close menu',
  a11y_open_menu: 'Open menu',
  a11y_user_menu: 'User menu',
  a11y_language_selector: 'Language selector',
  a11y_search: 'Search',
  a11y_notifications: 'Notifications',
  a11y_cart: 'Cart',
  a11y_logo: 'Voiago logo',
  a11y_back_to_top: 'Back to top',
  a11y_loading: 'Loading content',
  a11y_expanded: 'Expanded',
  a11y_collapsed: 'Collapsed',
};

const arTranslations: Translations = {
  // Navigation
  nav_features: 'الميزات',
  nav_guides: 'الأدلة',
  nav_pricing: 'الأسعار',
  nav_partners: 'الشركاء',
  nav_login: 'تسجيل الدخول',
  nav_signup: 'إنشاء حساب',
  nav_dashboard: 'لوحة التحكم',
  nav_wallet: 'المحفظة',
  nav_trips: 'الرحلات',
  nav_emergency: 'الطوارئ',
  nav_settings: 'الإعدادات',
  nav_logout: 'تسجيل الخروج',
  nav_admin: 'المشرف',
  nav_partner: 'الشريك',
  nav_bookings: 'الحجوزات',
  nav_points: 'النقاط',
  nav_journal: 'المذكرات',

  // Hero
  hero_title: 'رفيقك الذكي للسفر',
  hero_subtitle: 'خطط، احجز، واستكشف مع توصيات مدعومة بالذكاء الاصطناعي، ورؤى السلامة في الوقت الفعلي، والمدفوعات المحلية السلسة.',
  hero_cta_primary: 'ابدأ رحلتك',
  hero_cta_secondary: 'شاهد العرض التوضيحي',
  hero_trust: 'موثوق به من قبل أكثر من 50,000 مسافر في الشرق الأوسط وأفريقيا',

  // Features
  features_title: 'كل ما تحتاجه للسفر بذكاء',
  features_subtitle: 'من التخطيط بالذكاء الاصطناعي إلى دعم الطوارئ، يغطي فوياجو كل جانب من رحلتك.',
  feature_ai_title: 'مخطط الرحلات بالذكاء الاصطناعي',
  feature_ai_desc: 'احصل على خطط سفر مخصصة في ثوانٍ. يفهم ذكاؤنا الاصطناعي تفضيلاتك والفروقات المحلية.',
  feature_wallet_title: 'محفظة السفر الذكية',
  feature_wallet_desc: 'تتبع النفقات، واقسم الفواتير، وإدارة الميزانيات عبر عملات متعددة بسهولة.',
  feature_safety_title: 'السلامة وSOS',
  feature_safety_desc: 'تنبيهات في الوقت الفعلي، وبروتوكولات طوارئ بدون إنترنت، ومشاركة الموقع الفورية مع جهات اتصال موثوقة.',
  feature_loyalty_title: 'الولاء والمكافآت',
  feature_loyalty_desc: 'اكسب نقاطاً مع كل حجز. افتح امتيازات حصرية وترقيات وخصومات شركاء.',

  // Travel Guides
  guides_title: 'أدلة السفر المنسقة',
  guides_subtitle: 'اكتشف الأماكن الخفية وأسرار المحليين من مجتمع المستكشفين لدينا.',
  guides_read_more: 'اقرأ الدليل',
  guides_min_read: 'دقيقة قراءة',

  // Pricing
  pricing_title: 'أسعار بسيطة وشفافة',
  pricing_subtitle: 'اختر الخطة التي تناسب أسلوب سفرك. بدون رسوم خفية.',
  pricing_starter: 'البداية',
  pricing_pro: 'احترافي',
  pricing_enterprise: 'مؤسسي',
  pricing_month: '/شهر',
  pricing_popular: 'الأكثر شيوعاً',
  pricing_get_started: 'ابدأ الآن',
  pricing_contact_sales: 'تواصل مع المبيعات',

  // Partners
  partners_title: 'كن شريكاً معنا',
  partners_subtitle: 'انضم إلى نظامنا البيئي من الفنادق ومشغلي الجولات ومقدمي التجارب المحلية.',
  partners_cta: 'كن شريكاً',

  // Footer
  footer_tagline: 'رفيقك الذكي للسفر في الشرق الأوسط وأفريقيا.',
  footer_product: 'المنتج',
  footer_company: 'الشركة',
  footer_legal: 'قانوني',
  footer_rights: 'جميع الحقوق محفوظة.',

  // Auth
  auth_welcome: 'مرحباً بعودتك',
  auth_welcome_sub: 'سجل الدخول للوصول إلى لوحة تحكم سفرك',
  auth_email: 'البريد الإلكتروني',
  auth_password: 'كلمة المرور',
  auth_sign_in: 'تسجيل الدخول',
  auth_no_account: 'ليس لديك حساب؟',
  auth_sign_up: 'إنشاء حساب',
  auth_forgot_password: 'نسيت كلمة المرور؟',
  auth_create_account: 'إنشاء حساب جديد',
  auth_name: 'الاسم الكامل',
  auth_confirm_password: 'تأكيد كلمة المرور',
  auth_have_account: 'لديك حساب بالفعل؟',
  auth_or_continue: 'أو تابع باستخدام',
  auth_traveler: 'مسافر',
  auth_partner_role: 'شريك',
  auth_admin: 'مشرف',
  auth_role_label: 'نوع الحساب',

  // Dashboard
  dashboard_welcome: 'مرحباً بعودتك',
  dashboard_subtitle: 'إليك نظرة عامة على نظام السفر الذكي الخاص بك',
  dashboard_itinerary: 'خط السير',
  dashboard_insights: 'رؤى',
  dashboard_upcoming: 'الرحلة القادمة',
  dashboard_days_until: 'يوم حتى المغادرة',
  dashboard_destination: 'الوجهة',
  dashboard_travelers: 'المسافرون',
  dashboard_budget: 'الميزانية',
  dashboard_spent: 'منفق',
  dashboard_view_details: 'عرض التفاصيل',
  dashboard_active_trip: 'رحلة نشطة',
  dashboard_wallet: 'المحفظة',
  dashboard_safety_status: 'حالة السلامة',
  dashboard_safety_safe: 'آمن',
  dashboard_safety_moderate: 'متوسط',
  dashboard_safety_alert: 'تنبيه',
  dashboard_recent_activity: 'النشاط الأخير',
  dashboard_no_activity: 'لا يوجد نشاط حديث',
  dashboard_explore_more: 'استكشف المزيد',
  dashboard_book_next: 'احجز مغامرتك القادمة',

  // Wallet
  wallet_title: 'محفظة السفر',
  wallet_subtitle: 'إدارة أموال سفرك',
  wallet_balance: 'الرصيد المتاح',
  wallet_add_funds: 'إضافة رصيد',
  wallet_send: 'إرسال',
  wallet_transactions: 'المعاملات',
  wallet_expenses: 'النفقات',
  wallet_all: 'الكل',
  wallet_credits: 'ائتمانات',
  wallet_debits: 'مدفوعات',
  wallet_no_transactions: 'لا توجد معاملات بعد',
  wallet_expense_breakdown: 'تفصيل النفقات',
  wallet_category_accommodation: 'الإقامة',
  wallet_category_food: 'الطعام والمطاعم',
  wallet_category_transport: 'المواصلات',
  wallet_category_activities: 'الأنشطة',
  wallet_category_shopping: 'التسوق',
  wallet_category_other: 'أخرى',

  // Trip Planner
  planner_title: 'مخطط الرحلات بالذكاء الاصطناعي',
  planner_subtitle: 'دع ذكاءنا الاصطناعي يرسم رحلتك المثالية',
  planner_destination: 'إلى أين تريد أن تذهب؟',
  planner_dates: 'تواريخ السفر',
  planner_travelers: 'عدد المسافرين',
  planner_budget: 'نطاق الميزانية',
  planner_preferences: 'التفضيلات',
  planner_generate: 'إنشاء خط السير',
  planner_generating: 'جاري الإنشاء...',
  planner_day: 'اليوم',
  planner_morning: 'الصباح',
  planner_afternoon: 'بعد الظهر',
  planner_evening: 'المساء',
  planner_save_trip: 'حفظ الرحلة',
  planner_share: 'مشاركة',
  planner_modify: 'تعديل',

  // Emergency
  emergency_title: 'مركز الطوارئ',
  emergency_subtitle: 'وصول سريع إلى أدوات السلامة وجهات اتصال الطوارئ',
  emergency_sos: 'تنبيه SOS',
  emergency_sos_desc: 'أرسل تنبيهاً فورياً مع موقعك',
  emergency_contacts: 'جهات اتصال الطوارئ',
  emergency_local_police: 'الشرطة المحلية',
  emergency_ambulance: 'الإسعاف',
  emergency_embassy: 'السفارة',
  emergency_share_location: 'مشاركة الموقع',
  emergency_safety_map: 'خريطة السلامة',
  emergency_status: 'الحالة',
  emergency_last_updated: 'آخر تحديث',

  // Settings
  settings_title: 'الإعدادات',
  settings_subtitle: 'إدارة تفضيلات حسابك',
  settings_profile: 'الملف الشخصي',
  settings_notifications: 'الإشعارات',
  settings_privacy: 'الخصوصية',
  settings_language: 'اللغة',
  settings_currency: 'العملة',
  settings_save: 'حفظ التغييرات',
  settings_cancel: 'إلغاء',
  settings_edit: 'تعديل',
  settings_name: 'الاسم',
  settings_email: 'البريد الإلكتروني',
  settings_phone: 'الهاتف',
  settings_bio: 'نبذة',

  // Points
  points_title: 'نقاط الولاء',
  points_subtitle: 'تتبع واستبدل مكافآتك',
  points_balance: 'رصيد النقاط',
  points_history: 'سجل النقاط',
  points_redeem: 'استبدال',
  points_earn_more: 'اكسب المزيد',
  points_tier: 'المستوى',
  points_next_tier: 'نقطة للمستوى التالي',

  // Journal
  journal_title: 'مذكرات السفر',
  journal_subtitle: 'التقط وشارك ذكريات سفرك',
  journal_new_entry: 'إدخال جديد',
  journal_no_entries: 'لا توجد إدخالات بعد',
  journal_write_first: 'اكتب إدخالك الأول',
  journal_date: 'التاريخ',
  journal_location: 'الموقع',
  journal_mood: 'المزاج',
  journal_tags: 'الوسوم',

  // Bookings
  bookings_title: 'حجوزاتي',
  bookings_subtitle: 'إدارة رحلاتك القادمة والسابقة',
  bookings_upcoming: 'القادمة',
  bookings_past: 'السابقة',
  bookings_cancelled: 'الملغاة',
  bookings_no_bookings: 'لا توجد حجوزات',
  bookings_book_now: 'احجز الآن',
  bookings_details: 'التفاصيل',
  bookings_cancel: 'إلغاء',
  bookings_modify: 'تعديل',

  // Admin
  admin_title: 'لوحة تحكم المشرف',
  admin_subtitle: 'إدارة عمليات المنصة',
  admin_users: 'المستخدمون',
  admin_partners: 'الشركاء',
  admin_bookings: 'الحجوزات',
  admin_revenue: 'الإيرادات',
  admin_analytics: 'التحليلات',
  admin_support: 'تذاكر الدعم',

  // Partner
  partner_title: 'لوحة تحكم الشريك',
  partner_subtitle: 'إدارة قوائمك وحجوزاتك',
  partner_listings: 'قوائمي',
  partner_bookings: 'الحجوزات',
  partner_reviews: 'التقييمات',
  partner_analytics: 'التحليلات',
  partner_payouts: 'المدفوعات',

  // AI Chatbot
  chat_title: 'فوياجو AI',
  chat_placeholder: 'اسألني أي شيء عن رحلتك...',
  chat_send: 'إرسال',
  chat_suggestions: 'اقتراحات',
  chat_plan_trip: 'خطط لرحلة',
  chat_find_hotels: 'ابحث عن فنادق',
  chat_safety_info: 'معلومات السلامة',
  chat_clear: 'مسح المحادثة',

  // Common
  common_loading: 'جاري التحميل...',
  common_error: 'حدث خطأ ما',
  common_retry: 'إعادة المحاولة',
  common_save: 'حفظ',
  common_delete: 'حذف',
  common_edit: 'تعديل',
  common_cancel: 'إلغاء',
  common_confirm: 'تأكيد',
  common_back: 'رجوع',
  common_next: 'التالي',
  common_done: 'تم',
  common_search: 'بحث',
  common_filter: 'تصفية',
  common_sort: 'ترتيب',
  common_view_all: 'عرض الكل',
  common_show_more: 'عرض المزيد',
  common_show_less: 'عرض أقل',
  common_read_more: 'اقرأ المزيد',
  common_learn_more: 'اعرف المزيد',
  common_get_started: 'ابدأ الآن',
  common_contact: 'تواصل',
  common_help: 'مساعدة',
  common_support: 'الدعم',
  common_feedback: 'ملاحظات',
  common_share: 'مشاركة',
  common_copy: 'نسخ',
  common_copied: 'تم النسخ!',
  common_close: 'إغلاق',
  common_open: 'فتح',
  common_select: 'اختيار',
  common_choose: 'اختر',
  common_apply: 'تطبيق',
  common_reset: 'إعادة تعيين',
  common_update: 'تحديث',
  common_remove: 'إزالة',
  common_add: 'إضافة',
  common_create: 'إنشاء',
  common_new: 'جديد',
  common_active: 'نشط',
  common_inactive: 'غير نشط',
  common_pending: 'معلق',
  common_completed: 'مكتمل',
  common_failed: 'فشل',
  common_success: 'نجاح',
  common_warning: 'تحذير',
  common_info: 'معلومات',
  common_error_occurred: 'حدث خطأ',
  common_try_again: 'يرجى المحاولة مرة أخرى',
  common_no_results: 'لا توجد نتائج',
  common_empty_state: 'لا يوجد شيء هنا بعد',
  common_coming_soon: 'قريباً',
  common_beta: 'تجريبي',
  common_new_feature: 'ميزة جديدة',
  common_popular: 'شائع',
  common_recommended: 'موصى به',
  common_featured: 'مميز',
  common_exclusive: 'حصري',
  common_limited: 'وقت محدود',
  common_free: 'مجاني',
  common_premium: 'مميز',
  common_pro: 'احترافي',
  common_basic: 'أساسي',
  common_standard: 'قياسي',
  common_enterprise: 'مؤسسي',
  common_monthly: 'شهري',
  common_yearly: 'سنوي',
  common_per_month: 'في الشهر',
  common_per_year: 'في السنة',
  common_start_free: 'ابدأ تجربة مجانية',
  common_upgrade: 'ترقية',
  common_downgrade: 'تخفيض',
  common_manage: 'إدارة',
  common_configure: 'إعداد',
  common_customize: 'تخصيص',
  common_personalize: 'ت personalization',
  common_secure: 'آمن',
  common_private: 'خاص',
  common_public: 'عام',
  common_visible: 'مرئي',
  common_hidden: 'مخفي',
  common_enabled: 'مفعل',
  common_disabled: 'معطل',
  common_on: 'تشغيل',
  common_off: 'إيقاف',
  common_yes: 'نعم',
  common_no: 'لا',
  common_ok: 'موافق',
  common_continue: 'متابعة',
  common_skip: 'تخطي',
  common_back_to_home: 'العودة للرئيسية',
  common_go_to_dashboard: 'الذهاب إلى لوحة التحكم',
  common_explore: 'استكشاف',
  common_discover: 'اكتشاف',
  common_plan: 'تخطيط',
  common_book: 'حجز',
  common_track: 'تتبع',
  common_manage_account: 'إدارة الحساب',
  common_profile_settings: 'إعدادات الملف الشخصي',
  common_account_settings: 'إعدادات الحساب',
  common_notification_settings: 'إعدادات الإشعارات',
  common_privacy_settings: 'إعدادات الخصوصية',
  common_security_settings: 'إعدادات الأمان',
  common_language_settings: 'إعدادات اللغة',
  common_currency_settings: 'إعدادات العملة',
  common_payment_methods: 'طرق الدفع',
  common_billing: 'الفوترة',
  common_subscription: 'الاشتراك',
  common_invite_friends: 'دعوة الأصدقاء',
  common_help_center: 'مركز المساعدة',
  common_terms: 'شروط الخدمة',
  common_privacy_policy: 'سياسة الخصوصية',
  common_cookies: 'سياسة ملفات تعريف الارتباط',
  common_accessibility: 'إمكانية الوصول',
  common_about: 'عن الشركة',
  common_careers: 'الوظائف',
  common_press: 'الصحافة',
  common_blog: 'المدونة',
  common_contact_us: 'تواصل معنا',

  // Notifications
  notif_title: 'الإشعارات',
  notif_mark_all_read: 'تحديد الكل كمقروء',
  notif_clear_all: 'مسح الكل',
  notif_no_notifications: 'لا توجد إشعارات',
  notif_flight_reminder: 'تذكير بالرحلة',
  notif_check_in: 'فتح تسجيل الوصول',
  notif_safety_alert: 'تنبيه السلامة',
  notif_points_earned: 'نقاط مكتسبة',
  notif_booking_confirmed: 'تم تأكيد الحجز',
  notif_payment_received: 'تم استلام الدفع',
  notif_new_message: 'رسالة جديدة',
  notif_trip_update: 'تحديث الرحلة',
  notif_weather_alert: 'تنبيه الطقس',
  notif_promo: 'عرض خاص',

  // Additional keys
  common_sustainability: 'درجة الاستدامة',
  common_rating: 'التقييم',
  common_places: 'أماكن',
  common_traveler: 'مسافر',
  common_quick_actions: 'إجراءات سريعة',
  common_total: 'المجموع',
  common_adventure: 'مغامرة',
  common_culture: 'ثقافة',
  common_food: 'طعام',
  common_nature: 'طبيعة',
  common_relaxation: 'استرخاء',
  common_nightlife: 'حياة ليلية',
  common_budget: 'ميزانية',
  common_luxury: 'فاخر',
  common_days: 'أيام',
  common_activities: 'أنشطة',
  common_all: 'الكل',
  common_challenges: 'تحديات',
  common_tiers: 'مستويات',
  common_progress: 'التقدم',
  common_min: 'حد أدنى',
  common_points: 'نقاط',
  common_book_hotel: 'احجز فندق',
  common_write_review: 'اكتب تقييم',
  common_refer_friend: 'أوصِ صديقاً',
  common_guests: 'ضيوف',
  common_start_exploring: 'ابدأ الاستكشاف لحجز رحلتك الأولى',
  common_access_denied: 'الوصول مرفوض',
  common_admin_only: 'للمشرفين فقط',
  common_partner_only: 'للشركاء فقط',
  common_overview: 'نظرة عامة',
  common_last_30_days: 'آخر 30 يوم',
  common_last_90_days: 'آخر 90 يوم',
  common_last_year: 'آخر سنة',
  common_chart_coming_soon: 'التصور البياني قريباً',
  common_system_health: 'صحة النظام',
  common_api_status: 'حالة API',
  common_database: 'قاعدة البيانات',
  common_cdn: 'CDN',
  common_operational: 'يعمل',
  common_manage_users: 'إدارة المستخدمين',
  common_approve_partners: 'الموافقة على الشركاء',
  common_process_payouts: 'معالجة المدفوعات',
  common_add_listing: 'إضافة قائمة',
  common_view_payouts: 'عرض المدفوعات',
  common_view_reviews: 'عرض التقييمات',
  common_available: 'متاح',
  common_total_earned: 'إجمالي المكتسب',
  common_request_payout: 'طلب دفع',
  common_map_loading: 'جاري تحميل الخريطة',
  common_map_coming_soon: 'الخريطة التفاعلية قريباً',
  common_layer: 'طبقة',
  common_safe: 'آمن',
  common_caution: 'حذر',
  common_alert: 'تنبيه',
  common_activate: 'تفعيل',
  common_sharing_location_in: 'مشاركة الموقع خلال',
  common_location_shared: 'تم مشاركة الموقع',
  common_contacts_notified: 'تم إخطار جهات الاتصال',
  common_share_again: 'مشاركة مرة أخرى',
  common_spent: 'منفق',
  common_english: 'الإنجليزية',
  common_arabic: 'العربية',
  common_saved: 'تم الحفظ',
  privacy_location: 'مشاركة الموقع',
  privacy_location_desc: 'شارك موقعك مع جهات اتصال موثوقة',
  privacy_profile: 'رؤية الملف الشخصي',
  privacy_profile_desc: 'تحكم من يمكنه رؤية ملفك الشخصي',
  privacy_data: 'استخدام البيانات',
  privacy_data_desc: 'إدارة كيفية استخدام بياناتك',
  notif_flight_desc: 'رحلتك إلى القاهرة تقلع خلال 24 ساعة',
  notif_checkin_desc: 'تسجيل الوصول متاح الآن لحجزك',
  notif_safety_desc: 'تنبيه طقس في منطقة وجهتك',
  notif_points_desc: 'ربحت 500 نقطة لحجزك الأخير',
  notif_promo_desc: 'احصل على خصم 20% لحجزك القادم',
  settings_profile_desc: 'تحديث معلوماتك الشخصية',
  journal_entry_title: 'عنوان الإدخال',
  journal_write_your_thoughts: 'اكتب أفكارك...',
  journal_tags_placeholder: 'أضف وسوم مفصولة بفواصل',

  // Accessibility
  a11y_skip_to_content: 'تخطي إلى المحتوى الرئيسي',
  a11y_menu: 'القائمة',
  a11y_close_menu: 'إغلاق القائمة',
  a11y_open_menu: 'فتح القائمة',
  a11y_user_menu: 'قائمة المستخدم',
  a11y_language_selector: 'محدد اللغة',
  a11y_search: 'بحث',
  a11y_notifications: 'إشعارات',
  a11y_cart: 'سلة التسوق',
  a11y_logo: 'شعار فوياجو',
  a11y_back_to_top: 'العودة للأعلى',
  a11y_loading: 'جاري تحميل المحتوى',
  a11y_expanded: 'موسع',
  a11y_collapsed: 'مطوي',
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('voiago_language') as Language;
      if (stored === 'ar' || stored === 'en') return stored;
    }
    return 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('voiago_language', language);
      document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translations = language === 'ar' ? arTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
