import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'navbar.home': 'Home',
    'navbar.about': 'About',
    'navbar.partners': 'Partners',
    'navbar.contact': 'Contact',
    'landing.hero.title': 'Explore the World with Voiago',
    'landing.hero.subtitle': 'Your Gateway to Premium Travel Experiences Worldwide',
    'landing.hero.cta': 'Start Planning',
    'auth.welcome': 'Welcome to Voiago',
    'auth.title.signin': 'Sign in',
    'auth.title.signup': 'Create account',
    'auth.subtitle.signin': 'Sign in to view your trips, bookings and rewards.',
    'auth.subtitle.signup': 'Create an account to start crafting your next escape.',
    'auth.select_role': 'Select role',
    'auth.role.traveler': 'Traveler',
    'auth.role.admin': 'Admin',
    'auth.fullname': 'Full name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.currency': 'Preferred Currency',
    'auth.language': 'Preferred Language',
    'auth.button.signin': 'Sign in',
    'auth.button.signup': 'Create my account',
    'auth.terms_text': "By continuing you agree to Voiago's",
    'auth.terms_link': 'Terms',
    'auth.privacy_link': 'Privacy',
    'dashboard.total_bookings': 'Total Bookings',
    'dashboard.this_month': 'This Month',
    'dashboard.net_revenue': 'Net Revenue',
    'dashboard.generated': 'Generated',
    'dashboard.commission_rate': 'Commission Rate',
    'dashboard.guest_satisfaction': 'Guest Satisfaction',
    'dashboard.out_of_five': 'Out of 5.0',
    'emergency.title': 'Emergency Hub',
    'emergency.subtitle': 'Stay safe with instant access to emergency services',
    'emergency.select_country': 'Select Country',
    'emergency.emergency_number': 'Emergency Number',
    'emergency.police': 'Police',
    'emergency.ambulance': 'Ambulance',
    'emergency.fire': 'Fire Department',
    'emergency.safety_tips': 'Safety Tips',
    'emergency.share_location': 'Share My Location',
    'emergency.location_shared': 'Location Shared Successfully',
    'emergency.safety_map': 'Safety Map',
    'emergency.emergency_status': 'Emergency Status',
    'trip_planner.title': 'Smart Trip Planner',
    'trip_planner.subtitle': 'Plan your perfect trip with AI-powered suggestions',
    'trip_planner.destination': 'Destination',
    'trip_planner.destination_placeholder': 'Where do you want to go?',
    'trip_planner.budget': 'Budget',
    'trip_planner.budget_placeholder': 'Enter your budget',
    'trip_planner.days': 'Number of Days',
    'trip_planner.days_placeholder': 'How many days?',
    'trip_planner.plan_button': 'Generate Plan',
    'trip_planner.budget_breakdown': 'Budget Breakdown',
    'trip_planner.accommodation': 'Accommodation',
    'trip_planner.food': 'Food & Dining',
    'trip_planner.transportation': 'Transportation',
    'trip_planner.activities': 'Activities',
    'trip_planner.miscellaneous': 'Miscellaneous',
    'wallet.title': 'Wallet & Budget',
    'wallet.subtitle': 'Manage your finances and track expenses',
    'wallet.available_balance': 'Available Balance',
    'wallet.cashback': 'Cashback Earned',
    'wallet.smart_insights': 'Smart Insights',
    'wallet.manage_assets': 'Manage Digital Assets',
    'wallet.view_transactions': 'View Transactions',
    'bookings.title': 'My Bookings',
    'bookings.subtitle': 'View and manage your reservations',
    'bookings.search': 'Search bookings...',
    'bookings.filter': 'Filter',
    'bookings.all': 'All',
    'bookings.upcoming': 'Upcoming',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'bookings.status': 'Status',
    'bookings.date': 'Date',
    'bookings.destination': 'Destination',
    'journal.title': 'Travel Journal',
    'journal.subtitle': 'Document your travel memories',
    'journal.add_entry': 'Add Entry',
    'journal.place': 'Place',
    'journal.date': 'Date',
    'journal.notes': 'Notes',
    'journal.photos': 'Photos',
    'journal.save': 'Save Entry',
    'points.title': 'Loyalty & Guides',
    'points.subtitle': 'Unlock rewards and discover premium travel experiences',
    'points.redeem_points': 'Redeem Your Points',
    'points.rewards_store': 'Rewards Store',
    'points.travel_guides': 'Travel Guides',
    'settings.title': 'Settings',
    'settings.subtitle': 'Tailor Voiago to you',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.preferences': 'Preferences',
    'settings.security': 'Security',
    'settings.subscription': 'Subscription',
    'settings.change_photo': 'Change photo',
    'settings.first_name': 'First name',
    'settings.last_name': 'Last name',
    'settings.about': 'About',
    'settings.save_changes': 'Save changes',
    'settings.booking_confirmations': 'Booking confirmations',
    'settings.trip_reminders': 'Trip reminders',
    'settings.personalized_deals': 'Personalized deals',
    'settings.newsletter': 'Newsletter',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.theme': 'Theme',
    'settings.current_password': 'Current password',
    'settings.new_password': 'New password',
    'settings.confirm_password': 'Confirm new password',
    'settings.update_password': 'Update password',
    'settings.current_plan': 'Current plan',
    'settings.manage': 'Manage',
    'settings.cancel': 'Cancel',
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage platform operations',
    'admin.signin_title': 'Admin Sign In',
    'admin.signup_title': 'Admin Sign Up',
    'admin.email': 'Admin Email',
    'admin.password': 'Admin Password',
    'admin.login': 'Login',
    'admin.register': 'Register',
    'partner.title': 'Join Voiago Partners',
    'partner.subtitle': "Grow your business with the world's leading travel platform.",
    'partner.form_title': 'Start Your Partnership Today',
    'partner.form_subtitle': "Fill out the form and our team will reach out within 24 hours",
    'partner.business_name': 'Business Name',
    'partner.business_name_placeholder': 'Your Business Name',
    'partner.service_type': 'Service Type',
    'partner.service_type_select': 'Select your service type',
    'partner.hotel': 'Hotel & Accommodation',
    'partner.airline': 'Airline & Transportation',
    'partner.experience': 'Experience & Activity',
    'partner.dining': 'Dining & Restaurant',
    'partner.other_service': 'Other Service',
    'partner.email': 'Corporate Email',
    'partner.email_placeholder': 'your@company.com',
    'partner.submit': 'Become a Partner',
    'partner.submitted': 'Application Submitted!',
    'partner.terms': 'By submitting, you agree to our Terms of Service and Privacy Policy',
    'chatbot.title': 'Voiago AI Concierge',
    'chatbot.send': 'Send',
    'chatbot.typing': 'Voiago is typing...',
    'partner_dashboard.title': 'Partner Hub',
    'partner_dashboard.subtitle': 'Welcome back, Partner Overview',
    'partner_dashboard.analytics': 'Analytics',
    'partner_dashboard.earnings': 'Earnings',
    'partner_dashboard.reviews': 'Reviews',
  },
  ar: {
    'navbar.home': 'الرئيسية',
    'navbar.about': 'معلومات عنا',
    'navbar.partners': 'الشركاء',
    'navbar.contact': 'اتصل بنا',
    'landing.hero.title': 'اكتشف العالم مع فويآجو',
    'landing.hero.subtitle': 'بوابتك إلى تجارب السفر الفاخرة حول العالم',
    'landing.hero.cta': 'ابدأ التخطيط',
    'auth.welcome': 'مرحباً بك في فويآجو',
    'auth.title.signin': 'تسجيل الدخول',
    'auth.title.signup': 'إنشاء حساب',
    'auth.subtitle.signin': 'سجل دخولك لاستعراض رحلاتك وحجوزاتك ومكافآتك.',
    'auth.subtitle.signup': 'أنشئ حساباً جديداً لتبدأ بالتخطيط لرحلتك القادمة.',
    'auth.select_role': 'اختر الصلاحية',
    'auth.role.traveler': 'مسافر',
    'auth.role.admin': 'مسؤول النظام',
    'auth.fullname': 'الاسم الكامل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.currency': 'العملة المفضلة',
    'auth.language': 'اللغة المفضلة',
    'auth.button.signin': 'تسجيل الدخول',
    'auth.button.signup': 'إنشاء حسابي الجديد',
    'auth.terms_text': 'باستمرارك، فإنك توافق على فويآجو',
    'auth.terms_link': 'الشروط والأحكام',
    'auth.privacy_link': 'سياسة الخصوصية',
    'dashboard.total_bookings': 'إجمالي الحجوزات',
    'dashboard.this_month': 'هذا الشهر',
    'dashboard.net_revenue': 'صافي الإيراد',
    'dashboard.generated': 'المُولّد',
    'dashboard.commission_rate': 'معدل العمولة',
    'dashboard.guest_satisfaction': 'رضا الضيف',
    'dashboard.out_of_five': 'من 5.0',
    'emergency.title': 'مركز الطوارئ',
    'emergency.subtitle': 'ابقَ آمناً مع الوصول الفوري لخدمات الطوارئ',
    'emergency.select_country': 'اختر الدولة',
    'emergency.emergency_number': 'رقم الطوارئ',
    'emergency.police': 'الشرطة',
    'emergency.ambulance': 'الإسعاف',
    'emergency.fire': 'الإطفاء',
    'emergency.safety_tips': 'نصائح الأمان',
    'emergency.share_location': 'شارك موقعي',
    'emergency.location_shared': 'تم مشاركة الموقع بنجاح',
    'emergency.safety_map': 'خريطة الأمان',
    'emergency.emergency_status': 'حالة الطوارئ',
    'trip_planner.title': 'مخطط الرحلات الذكي',
    'trip_planner.subtitle': 'خطط رحلتك المثالية مع اقتراحات مدعومة بالذكاء الاصطناعي',
    'trip_planner.destination': 'الوجهة',
    'trip_planner.destination_placeholder': 'إلى أين تريد الذهاب؟',
    'trip_planner.budget': 'الميزانية',
    'trip_planner.budget_placeholder': 'أدخل ميزانيتك',
    'trip_planner.days': 'عدد الأيام',
    'trip_planner.days_placeholder': 'كم يوماً؟',
    'trip_planner.plan_button': 'إنشاء الخطة',
    'trip_planner.budget_breakdown': 'تفصيل الميزانية',
    'trip_planner.accommodation': 'الإقامة',
    'trip_planner.food': 'الطعام والمطاعم',
    'trip_planner.transportation': 'النقل',
    'trip_planner.activities': 'الأنشطة',
    'trip_planner.miscellaneous': 'متفرقات',
    'wallet.title': 'المحفظة والميزانية',
    'wallet.subtitle': 'أدر أموالك وتتبع المصاريف',
    'wallet.available_balance': 'الرصيد المتاح',
    'wallet.cashback': 'استرداد الأموال المكتسب',
    'wallet.smart_insights': 'رؤى ذكية',
    'wallet.manage_assets': 'إدارة الأصول الرقمية',
    'wallet.view_transactions': 'عرض المعاملات',
    'bookings.title': 'حجوزاتي',
    'bookings.subtitle': 'اعرض وأدر حجوزاتك',
    'bookings.search': 'بحث في الحجوزات...',
    'bookings.filter': 'تصفية',
    'bookings.all': 'الكل',
    'bookings.upcoming': 'القادمة',
    'bookings.completed': 'المكتملة',
    'bookings.cancelled': 'الملغاة',
    'bookings.status': 'الحالة',
    'bookings.date': 'التاريخ',
    'bookings.destination': 'الوجهة',
    'journal.title': 'يومية السفر',
    'journal.subtitle': 'وثق ذكريات سفرك',
    'journal.add_entry': 'إضافة إدخال',
    'journal.place': 'المكان',
    'journal.date': 'التاريخ',
    'journal.notes': 'الملاحظات',
    'journal.photos': 'الصور',
    'journal.save': 'حفظ الإدخال',
    'points.title': 'الولاء والأدلة',
    'points.subtitle': 'افتح المكافآت واكتشف تجارب السفر الفاخرة',
    'points.redeem_points': 'استبدال نقاطك',
    'points.rewards_store': 'متجر المكافآت',
    'points.travel_guides': 'أدلة السفر',
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'خصص فويآجو حسب احتياجاتك',
    'settings.profile': 'الملف الشخصي',
    'settings.notifications': 'الإشعارات',
    'settings.preferences': 'التفضيلات',
    'settings.security': 'الأمان',
    'settings.subscription': 'الاشتراك',
    'settings.change_photo': 'تغيير الصورة',
    'settings.first_name': 'الاسم الأول',
    'settings.last_name': 'اسم العائلة',
    'settings.about': 'عن',
    'settings.save_changes': 'حفظ التغييرات',
    'settings.booking_confirmations': 'تأكيدات الحجز',
    'settings.trip_reminders': 'تذكيرات الرحلة',
    'settings.personalized_deals': 'عروض مخصصة',
    'settings.newsletter': 'النشرة الإخبارية',
    'settings.language': 'اللغة',
    'settings.currency': 'العملة',
    'settings.theme': 'المظهر',
    'settings.current_password': 'كلمة المرور الحالية',
    'settings.new_password': 'كلمة المرور الجديدة',
    'settings.confirm_password': 'تأكيد كلمة المرور',
    'settings.update_password': 'تحديث كلمة المرور',
    'settings.current_plan': 'الخطة الحالية',
    'settings.manage': 'إدارة',
    'settings.cancel': 'إلغاء',
    'admin.title': 'لوحة تحكم المسؤول',
    'admin.subtitle': 'إدارة عمليات المنصة',
    'admin.signin_title': 'تسجيل دخول المسؤول',
    'admin.signup_title': 'تسجيل مسؤول جديد',
    'admin.email': 'بريد المسؤول الإلكتروني',
    'admin.password': 'كلمة مرور المسؤول',
    'admin.login': 'تسجيل الدخول',
    'admin.register': 'تسجيل',
    'partner.title': 'انضم إلى شركاء فويآجو',
    'partner.subtitle': 'نمِ عملك مع منصة السفر الرائدة عالمياً.',
    'partner.form_title': 'ابدأ شراكتك اليوم',
    'partner.form_subtitle': 'أملأ النموذج وسيعود إليك فريقنا في غضون 24 ساعة',
    'partner.business_name': 'اسم الشركة',
    'partner.business_name_placeholder': 'اسم شركتك',
    'partner.service_type': 'نوع الخدمة',
    'partner.service_type_select': 'اختر نوع خدمتك',
    'partner.hotel': 'الفندق والإقامة',
    'partner.airline': 'الخطوط الجوية والنقل',
    'partner.experience': 'التجارب والأنشطة',
    'partner.dining': 'الطعام والمطاعم',
    'partner.other_service': 'خدمة أخرى',
    'partner.email': 'البريد الإلكتروني للشركة',
    'partner.email_placeholder': 'your@company.com',
    'partner.submit': 'أصبح شريكاً',
    'partner.submitted': 'تم إرسال الطلب!',
    'partner.terms': 'بالموافقة، فإنك توافق على شروطنا وسياسة الخصوصية',
    'chatbot.title': 'مساعد فويآجو الذكي',
    'chatbot.send': 'إرسال',
    'chatbot.typing': 'فويآجو يكتب...',
    'partner_dashboard.title': 'مركز الشركاء',
    'partner_dashboard.subtitle': 'مرحباً بعودتك',
    'partner_dashboard.analytics': 'التحليلات',
    'partner_dashboard.earnings': 'الأرباح',
    'partner_dashboard.reviews': 'التقييمات',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLang] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('voiago_language') as Language | null;
    const initial = saved || 'en';
    setLang(initial);
    applyDir(initial);
  }, []);

  const applyDir = (lang: Language) => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const setLanguage = (lang: Language) => {
    setLang(lang);
    localStorage.setItem('voiago_language', lang);
    applyDir(lang);
  };

  const t = (key: string): string =>
    translations[language][key] ?? translations['en'][key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
