/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router
import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PartnerDashboardRouteImport } from './routes/partner-dashboard'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({ id: '/wallet', path: '/wallet', getParentRoute: () => rootRouteImport } as any)
const TripPlannerRoute = TripPlannerRouteImport.update({ id: '/trip-planner', path: '/trip-planner', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const PointsRoute = PointsRouteImport.update({ id: '/points', path: '/points', getParentRoute: () => rootRouteImport } as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({ id: '/partner-dashboard', path: '/partner-dashboard', getParentRoute: () => rootRouteImport } as any)
const JournalRoute = JournalRouteImport.update({ id: '/journal', path: '/journal', getParentRoute: () => rootRouteImport } as any)
const EmergencyRoute = EmergencyRouteImport.update({ id: '/emergency', path: '/emergency', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const BookingsRoute = BookingsRouteImport.update({ id: '/bookings', path: '/bookings', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/journal': typeof JournalRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/points': typeof PointsRoute
  '/settings': typeof SettingsRoute
  '/trip-planner': typeof TripPlannerRoute
  '/wallet': typeof WalletRoute
}

const rootRouteChildren = {
  IndexRoute,
  AdminRoute,
  AuthRoute,
  BookingsRoute,
  DashboardRoute,
  EmergencyRoute,
  JournalRoute,
  PartnerDashboardRoute,
  PointsRoute,
  SettingsRoute,
  TripPlannerRoute,
  WalletRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRoutesByFullPath>()
